spring.application.name=MafiaPlatformGatewayService
spring.jpa.properties.hibernate.show_sql=${HIBERNATE_SHOW_SQL:false}
spring.mvc.hiddenmethod.filter.enabled=true

security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME:36000000}

services.user.url=${USER_SERVICE_URL:http://localhost:8081}
services.user-management.host=${USER_MANAGEMENT_SERVICE_HOST:localhost}
services.user-management.port=${USER_MANAGEMENT_SERVICE_PORT:8060}

# Communication Service Configuration
services.communication.host=${COMMUNICATION_SERVICE_HOST:localhost}
services.communication.port=${COMMUNICATION_SERVICE_PORT:8080}

# Character Service Configuration
services.character.host=${CHARACTER_SERVICE_HOST:localhost}
services.character.port=${CHARACTER_SERVICE_PORT:8081}

# Town Service Configuration
services.town.host=${TOWN_SERVICE_HOST:localhost}
services.town.port=${TOWN_SERVICE_PORT:8080}

# Rumours Service Configuration
services.rumours.host=${RUMOURS_SERVICE_HOST:localhost}
services.rumours.port=${RUMOURS_SERVICE_PORT:8080}

# Game Service Configuration
services.game.host=${GAME_SERVICE_HOST:localhost}
services.game.port=${GAME_SERVICE_PORT:80}

spring.config.import=optional:file:.env[.properties]

server.address=0.0.0.0
server.port=8080

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.timeout=5000ms
spring.data.redis.connect-timeout=5000ms
spring.data.redis.database=0

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

resilience4j.bulkhead.instances.gatewayApi.max-concurrent-calls=20
resilience4j.bulkhead.instances.gatewayApi.max-wait-duration=50ms
