spring.application.name=LanguageGames
spring.jpa.properties.hibernate.show_sql=${HIBERNATE_SHOW_SQL:false}
spring.mvc.hiddenmethod.filter.enabled=true

security.jwt.secret-key =${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME:36000000}

services.user.url=${USER_SERVICE_URL:http://localhost:8081}

spring.config.import=optional:file:.env[.properties]

server.address=0.0.0.0
server.port=8080