services:
  redis-gateway:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --protected-mode no --appendonly yes
    volumes:
      - redis-gateway-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - app-network
    restart: unless-stopped

  db_town_service:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${TOWN_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TOWN_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TOWN_SERVICE_POSTGRES_DB}
    ports:
      - "${TOWN_SERVICE_POSTGRES_DB_PORT}:5432"
    volumes:
      - town_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TOWN_SERVICE_POSTGRES_USER} -d ${TOWN_SERVICE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db_character_service:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${CHARACTER_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${CHARACTER_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${CHARACTER_SERVICE_POSTGRES_DB}
    ports:
      - "${CHARACTER_SERVICE_POSTGRES_DB_PORT}:5432"
    volumes:
      - character_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CHARACTER_SERVICE_POSTGRES_USER} -d ${CHARACTER_SERVICE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  gateway-service:
#    image: dimaubuntu/gateway-service:latest
    build: .
    container_name: gateway-service
    ports:
      - "8088:8080"
    depends_on:
      redis-gateway:
        condition: service_healthy
    environment:
      - SPRING_REDIS_HOST=redis-gateway
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SERVICES_USER_URL=${SERVICES_USER_URL}
      - COMMUNICATION_SERVICE_HOST=communication-service
      - COMMUNICATION_SERVICE_PORT=8080
      - RUMOURS_SERVICE_HOST=rumours-service
      - RUMOURS_SERVICE_PORT=8080
      - CHARACTER_SERVICE_HOST=character-service
      - CHARACTER_SERVICE_PORT=8081
      - TOWN_SERVICE_HOST=town-service
      - TOWN_SERVICE_PORT=8080
    networks:
      - app-network

  town-service:
    image: dimaubuntu/town-service:latest
    environment:
      - TOWN_SERVICE_POSTGRES_HOST=db_town_service
      - TOWN_SERVICE_POSTGRES_DB_PORT=5432
      - TOWN_SERVICE_POSTGRES_USER=${TOWN_SERVICE_POSTGRES_USER}
      - TOWN_SERVICE_POSTGRES_PASSWORD=${TOWN_SERVICE_POSTGRES_PASSWORD}
      - TOWN_SERVICE_POSTGRES_DB=${TOWN_SERVICE_POSTGRES_DB}
      - SERVER_PORT=8080
    ports:
      - "8082:8080"
    depends_on:
      db_town_service:
        condition: service_healthy
    networks:
      - app-network

  character-service:
    image: dimaubuntu/character-service:latest
    container_name: character-service
    environment:
      - CHARACTER_SERVICE_POSTGRES_HOST=db_character_service
      - CHARACTER_SERVICE_POSTGRES_DB_PORT=5432
      - CHARACTER_SERVICE_POSTGRES_USER=${CHARACTER_SERVICE_POSTGRES_USER}
      - CHARACTER_SERVICE_POSTGRES_PASSWORD=${CHARACTER_SERVICE_POSTGRES_PASSWORD}
      - CHARACTER_SERVICE_POSTGRES_DB=${CHARACTER_SERVICE_POSTGRES_DB}
      - SERVER_PORT=8081
    ports:
      - "8083:8081"
    depends_on:
      db_character_service:
        condition: service_healthy
    networks:
      - app-network

  db_rumours_service:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${RUMOURS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${RUMOURS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${RUMOURS_POSTGRES_DB}
    ports:
      - "${RUMOURS_POSTGRES_DB_PORT}:5432"
    volumes:
      - rumours_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RUMOURS_POSTGRES_USER} -d ${RUMOURS_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rumours-service:
    image: m1rrerror/mafia-rumours-service:latest
    environment:
      DB_CONNECTION_STRING: "Host=db_rumours_service;Port=5432;Database=${RUMOURS_POSTGRES_DB};Username=${RUMOURS_POSTGRES_USER};Password=${RUMOURS_POSTGRES_PASSWORD}"
      CURRENCY_SERVICE_URL: ${CURRENCY_SERVICE_URL}
    ports:
      - "8084:8080"
    depends_on:
      db_rumours_service:
        condition: service_healthy
    networks:
      - app-network

  db_communication_service:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${COMM_POSTGRES_USER}
      POSTGRES_PASSWORD: ${COMM_POSTGRES_PASSWORD}
      POSTGRES_DB: ${COMM_POSTGRES_DB}
    ports:
      - "${COMM_POSTGRES_DB_PORT}:5432"
    volumes:
      - communication_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${COMM_POSTGRES_USER} -d ${COMM_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  communication-service:
    image: m1rrerror/mafia-communication-service:latest
    environment:
      ConnectionStrings__DefaultConnection: "Host=db_communication_service;Port=5432;Database=${COMM_POSTGRES_DB};Username=${COMM_POSTGRES_USER};Password=${COMM_POSTGRES_PASSWORD}"
    ports:
      - "8085:8080"
    depends_on:
      db_communication_service:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-gateway-data:
  town_postgres_data:
  character_postgres_data:
  rumours_postgres_data:
  communication_postgres_data: